### ISSUE TITLE
🐛 More missing school immune masks

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1020]
## 🐛 Bug report
https://classic.wowhead.com/npc=1043/lost-whelp#comments:id=44643:reply=108158
Should be immune to shadow.
https://www.wowhead.com/npc=1364/balgaras-the-foul#comments:id=1064073
Immune to shadow
https://www.wowhead.com/npc=2108/garneg-charskull#comments:id=30344:reply=343513
Immune to fire
https://www.wowhead.com/npc=2592/rumbling-exile#comments:id=828966
Immune to nature

Thanks to the trinitycore guys for those !
I have not personally tesed them on classic but there are multiple wowhead comments from vanilla to TLK reporting that they are immune.

### Expected behavior
They should be immune.

Having found an earth elemental that is not properly immune to nature, I guess a lot of them are wrong similar to the lava elementals.

### Version & Environment
Client Version: 1.12.1.5875

  Commit Hash:
latest

**Comment by offl** [comment]
Well, I checked today again comments for these and in 80-90% cases found comments about immunity
You can re-check them in game or re-check comments, just re-select them because those are TBC and WotLK too and some masks are already applied

-- 2
12457,16491,
-- 4
89,2091,2108,2447,2726,2760,4036,4037,4038,4676,5850,5852,7137,7734,7735,8317,9016,9017,9026,9816,9878,9879,10485,11502,11666,11667,11668,12056,12143,12457,15438,16491,19203,19973,21706,22323,20703,25001,25417,30847
-- 8
92,2258,2592,2735,2736,2752,2762,2791,4499,8317,10485,11321,11744,11777,11778,11783,11784,12201,12237,12457,14435,14455,15352,16491,17085,17154,17156,17157,17158,17159,17160,18062,18181,21707,23029,11779,22036,26407,28411,28585,28825
-- 16
510,691,2761,3917,5461,5462,7079,7132,7428,7429,7734,7735,8317,9453,10198,10485,10642,10756,10757,12457,13280,16491,17153,17155,17167,17358,19204,21428,21728,22009,22309,17207,26342,26341,26340,26339,26338,20704,22035,16570,25740,25755,25756,25757,25865,26116,26178,26204,26214,26215,26216,24228,24601,25226,25514,25715,26316,30846
-- 32
703,1043,1364,7734,7735,8317,10485,12457,16491,19206,21032,20705
-- 64
7734,7735,8317,10202,10485,10662,10663,10664,11480,11483,12457,16488,16491,16530,16854,18864,18865,18866,18867,19205,20516,21032,22310,20702,26370,30848

**Comment by T1ti** [comment]
I'm removing the BC/WOTLK creatures from your message : (the last creature ID in vanilla is 17996)
-- 2 (HOLY)
12457,16491,
-- 4 (FIRE)
89,2091,2108,2447,2726,2760,4036,4037,4038,4676,5850,5852,7137,7734,7735,8317,9016,9017,9026,9816,9878,9879,10485,11502,11666,11667,11668,12056,12143,12457,15438,16491
-- 8 (NATURE)
92,2258,2592,2735,2736,2752,2762,2791,4499,8317,10485,11321,11744,11777,11778,11783,11784,12201,12237,12457,14435,14455,15352,16491,17085,17154,17156,17157,17158,17159,17160
-- 16 (FROST)
510,691,2761,3917,5461,5462,7079,7132,7428,7429,7734,7735,8317,9453,10198,10485,10642,10756,10757,12457,13280,16491,17153,17155,17167,17358,19204,21428,21728,22009,22309,17207
-- 32 (SHADOW)
703,1043,1364,7734,7735,8317,10485,12457,16491
-- 64 (ARCANE)
7734,7735,8317,10202,10485,10662,10663,10664,11480,11483,12457,16488,16491,16530,16854

**Comment by offl** [comment]
TBC are still here

**Comment by T1ti** [comment]
Yep it looks like some TBC creatures have IDs similar to vanilla, due to TBC being in developement at the same time

**Comment by NickTyrer** [comment]
Colsed in #1467
