### ISSUE TITLE
[Quest] Missing Quest Script - Zamek's Distraction (1191)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1071]
Currently the script is missing for the quest, see https://www.youtube.com/watch?v=To45GI6_SFI for the correct behaviour.

Fix is here: https://github.com/cmangos/classic-db/commit/589e39fa18f41ff20b85de044cbedaf01d2e8619

Client Version: 1.12.1

Commit Hash:  4ee22bb

**Comment by ulfgebhardt** [comment]
Hey @NickTyrer - are you closing this since you have inluded that missing data into your `Misc database fixes` https://github.com/vmangos/core/pull/1036 PR? Or because they are no longer applicable?

**Comment by NickTyrer** [comment]
@ulfgebhardt yes, fix is included in the PR mentioned. Forgot to update the issue.

**Comment by ulfgebhardt** [comment]
Its common practice to close an issue as soon as the fix is in the `master` - in our case in the `development` - branch. One normally links the issue(s) a PR fixes within that PR. Github will link those automatically and if used in combination with keywords like `closes`or `fixes` will also close the corresponding issue upon merge. @NickTyrer

**Comment by ulfgebhardt** [comment]
fixed in #1036
