### ISSUE TITLE
🐛 [Bug] [Discussion] Accurate replication of Seal Twisting

### ISSUE THREAD

**Issue by YellowRyder** [vmangos/core#1075]
## 🐛 Bug report

Hello. I'd like to address several issues with the Custom Seal Twisting system that was added to vmangos. While I appreciate all the hard work done by the devs at attempting to recreate a true blizzlike experience, some things of course are more guess work than anything. Such is the case with Seal Twisting, the vanilla mechanic which was lost to the ages due to advancements in technology. The current pserv iteration neither matches the original vanilla twisting, nor does it match what Blizzard has given us on PTR.

### Expected behavior

Seal Twisting should work by activating a different seal than the current one activate right before you swing. This would cause both seals to be applied, as the seals were handled client-side which resulted in both being batched on the same hit. The method of replicating this in vmangos is brilliant - adding a "ghost aura" that persists 0.5 seconds after swapping seals. However, the current iteration has many shortcomings which keep it from being "blizzlike":

1.) Only SoC can be twisted. Although not much information exists regarding all the details of twisting, this is a key difference between vmangos iteration and blizzard PTR version. Neither are real vanilla, of course; simply artificial recreations. The vmangos devs state that no evidence exists of other seals besides SoC into X being twistable, yet blizzard seems to disagree with this. Their seal system allows any and all seals to be twisted on top of each other, provided you use different ranks, which would seemingly mirror the original vanilla twist mechanic of batching two seals on top of each other.

2.) Multiple ranks of SoC cannot be twisted. This is due to the custom aura used by vmangos to allow SoC to be twisted; It simply places an aura on the player when they remove SoC by swapping to a new seal, and does not account for individual ranks. The original vanilla twist would've batched two ranks of SoC together on a twist, checked both for procs, and issued a proc while triggering the ICD. This would make SoC unable to "double proc", but you could effectively double the proc chance of SoC by twisting two ranks together. The current version of vmangos twisting would need to be updated to apply the aura when twisting to a different rank of SoC; This would then allow the game to check both the aura and the new SoC rank on the swing.

3.) Twisting to a new seal and judging it right before the weapon swing removes the custom aura. This was intended to prevent players from receiving a SoC proc after judging it off; But it has the side effect of making the custom SoC aura dissipate when you judge a different seal after the twist but before the swing. This is an unintended deficiency in the new system that may have been overlooked in design.

As an aside; The single day in which the PPM flag was not placed on SoC and caused it to proc 100% of the time when you twisted it was the most fun and engaging dps rotation I've ever experienced in all of WoW. Every single correctly timed twist was rewarded with a tangible (although minor) increase to overall dps. It made the paladin dps rotation intricate, twisting seals carefully around the swing timer and having to think about the specific timings and interactions of each seal twisted was extremely enjoyable. I don't ask for vmangos core to implement this 100% proc, as it is indeed not vanilla; However, fixing the issue of SoC ranks twisting onto itself would go a very long way in helping fix a class that has been destroyed not only by malicious actors within Blizzard, but pserv devs who had accidentally scripted many paladin mechanics incorrectly over the years.

### Version & Environment

<!--
  Client Version:
  - 1.12.1.5875

**Comment by ulfgebhardt** [comment]
Hey @YellowRyder tho I have no clue if what you say is correct or not - you seem to have a very detailed knowledge of how spells currently work and how they should work. Furthermore you seem to have very decent knowledge of the inner workings of MaNGOS Spell system.

Can I ask you to visualize the state of the current system? Furthermore can I ask you to modify what you visualized so the newly modeled system could reflect the changes you suggest?

I ask this because the whole spell system is very complex and hard to understand. By visualizing it we could educate more people in understanding it and furthermore we would have a basis on which we can modify & (re)design it.
It is not required to model the entirety of the spell system nor is it required to be 100% correct on what you display, if you can provide us with a schema how to visualize it you would have made a great contribution we could work with <3

a good tool for visualizing systems is https://draw.io (also available as vs code/codium plugin)

Further more you imply having great pleasure with spells which are not 100% blizzlike but bring fun to the game mechanic. If you want to think and visualize a plugable system which would allow custom spells and custom spell overrides that would be appreciated as well

**Comment by Velite12** [comment]
Only Soc is supposed to be twisted. Seal twisting explicitly existed because SoC was not benefitting from Vengeance procs from the white hit that proc'd it. This behavior was added in Patch 1.11. Hence they added an internal delay to the seal so that it could appropriately get the benefit. The system on the ptr did not exist in 2006 era vanilla, this is something completely new that blizzard is doing. Also it is supposed to only be SoC and only 1 Rank of SoC. As a Paladin, as much as I'd love to have the PTR seal twisting system it did not exist before classic. So I don't think it would be conducive to accurately emulate Vanilla. That aside I personally think it solves paladin dps issues so Blizzard really likes it since it isn't easy to pull off, but that is a debate about design and not emulation accuracy.

Your point about judging the seal though needs to be looked at.

Also I agree on private servers misrepresenting paladins, which is why I worked on adding threat values to blessings in order to facilitate Protection paladins in raiding, as well as the dummy taunt. The performance and viability of paladins on private servers is severely hindered by incorrect scripting both for the class and for boss mechanics. As classic has displayed, paladins play completely differently and are not just set on being healers because of all of the behavior that Blizzard properly implemented.

The PTR system adds alot of depth and variety to an otherwise bland system of auto attack and afk


Patch 1.11.0 (20-Jun-2006):
Clarified tooltip.
Seal of Command critical hits can now trigger Vengeance.
            Since Patch 1.11, Seal of Command proc will have approximately 0.5 second delay before the animation begins and the Holy damage is incurred, instead of having the proc occur instantly with the swing of the attack. This is considered a good change, since if the normal swing is a critical strike and Vengeance is triggered, the Seal of Command proc will be affected by the buff.
https://wowwiki-archive.fandom.com/wiki/Seal_of_Command_(old)

**Comment by YellowRyder** [comment]
I did a bit of a diagram and writeup, attached here. It explains the underlying deficiencies with the current seal twist system on vmangos. Please take the time to read it for better understanding of exactly why seal twisting occurred in vanilla.

And again, I'd like to take this opportunity to thank the devs in pserv communities for their hard work. I know it is not the job of vmangos core devs to "improve" classes needlessly, but to retain the most true-to-vanilla experience possible. In this case, both goals can be met.

That being said, I would highly, HIGHLY encourage any of you reading this to load up stock vmangos on your own testbeds with the PPM removed from SoC custom aura, as Ratko suggested. With one simple thing, the entire retribution and protection specs are fixed beyond description - all without using any new abilities or cheap gimmicks. I think the 100% proc chance for SoC on correct twist fulfills the spirit of vanilla more than any "new" system we could create. It makes paladin gameplay challenging yet highly rewarding. It solves much of the ret dps issue and the prot threat issue without gimmicks. In PvE you are able to increase your output greatly when you time your abilities carefully, planning each next move ahead. It makes me think that this was something Blizzard had originally intended; Seal of Command is the only seal that is not baseline, it is mechanically unique and it exists solely as a DPS tool.

I'm not gonna beg here for it to be added into vmangos core because 100% SoC is indeed not vanilla. But if anything qualifies as the "push this button to fix this entire class", it is undoubtedly this. I do not say this lightly; it doesn't feel like a gimmick at all, which is what most "paladin tricks" feel like. The 100% proc reward for correct twisting was the most satisfying and "paladin-esque" dps rotation I have seen in 17 years of wow, including WotLK. And it was all because of a one-line mistake.

![twist](https://user-images.githubusercontent.com/77170734/108579609-c9047a80-72f5-11eb-8376-f21639ca17fb.png)

**Comment by Velite12** [comment]
So ultimately the problem is that because VMangos does not have batching, you can't twist multiple ranks of SoC? So "Seal Stacking" as it's called on classic (multiple rank twisting), was in 2006 due to batching? If so then this behavior can be replicated here artificially, and what you propose could be done (maybe not the 100% soc bit, that one is definitely something for custom). However it would just be multi rank SoC then (as opposed to multi-seal stacking of all seals), which would still go a long way for ret and prot. Moreso ret, since Blessing spam is still mandatory to tank certain encounters and both share the GCD.

So you indirectly found the irony of the paladin deficiency in vanilla: No buttons to press despite having so many spells! And now that you have buttons to press the class is good! Who'da thunk it.

The real question is: Can you find any evidence that this was happening with spell batching? Were people rank twisting in vanilla while spell batching was a 400 ms window?

**Comment by YellowRyder** [comment]
Again, we're in a weird place where right now as it stands on vmangos, seal twisting is okay. You can twist SoC into SotC for a tangible increase of damage, though this is technically not vanilla-like. I don't want to complain about it because it would just mean I get nerfed. If the system were changed to only allow SoC ranks and SoC>SoJ twisting (as was vanilla), we would receive a larger boost to DPS - but this would come at the cost of drastically simplifying the rotation into swapping back and forth between two ranks of SoC.

The current system is far more engaging; Depending on your weapon speed (fast 1h, slow 1h, fast 2h, slow 2h) your rotation varies greatly, along with the variance of circumstance. I'll find myself twisting SoC1>SotC>hit>judge>SoC1>hit>SotC>SoC5>judge>SoC1>repeat, while adding Light/Wisdom/Justice/Righteousness depending on the situation. It is very intricate, but often feels unrewarding when you don't get any procs. Sometimes, it performs the same as "traditional ret" except you're burning a ton of mana for literally no benefit.

If it were updated to true vanilla, it would simply be SoC1>SoC3>hit>repeat. Far less interesting but much more consistent numbers, and thus higher dps.

It's a tradeoff between what is more fun, what is more effective, and what is vanilla. And right now we're at a crossroads. If I had my own choice, I would give paladins the 100% proc on SoC because it simply felt so good to see your actions pay off with tangible results. The true vanilla-like twist mechanic would essentially be the same but far more boring; You're getting ~80% proc rate on SoC by simply twisting two ranks, as opposed to the intricate dps rotation of the 100% proc chance. The current system lies somewhere between the two; It is certainly more fun than just twisting two ranks, but feels far less rewarding than getting tangible results for each correct twist. In terms of damage output, the current system and the "true vanilla" system would have around the same output, with 100% proc system being a bit higher.

And as for evidence of two ranks of SoC twisting together, I cannot find any video footage but it is simply the logical conclusion of the system. And I don't think anyone was hyped to record it as it didn't (and shouldn't) allow multiple procs of SoC (like it did with Seal of Blood) because of ICD. It simply increased the proc rate, but the mechanic was generally unknown and no one seemed to really be using it until the numbers became more tangible in TBC with SoB.

**Comment by Velite12** [comment]
I was mostly experimenting with various proc items/sets with soc+sor twisting, which I think is the best way to use the system currently if your goal is to maximize proc chances. And yes, it adds alot of depth and engaging gameplay for an otherwise passive class. 

I guess the core of the question is, "What Defines the Vanilla Experience?". Is it accuracy or is it gameplay? What values should we aim for? With features that have very little information or no information, if we know that they existed in Vanilla, in which direction should we interpret implementing these features? Should we strictly follow how classic implements things?

While it certainly appears that most of the scripting gleamed from classic is indeed correct to 2006, and that certainly goes a long way towards emulating what was in 2006, should we adjust the accuracy to model the "desired experience"? 

Wrath of Cenarius is a really good example of this. A very obscure, rarely obtained and rarely documented item that has no recorded instance of uses with certain classes that could be modeled on VMangos. Nobody knows exactly how it worked in 2006, only Blizzard could tell you that, but the real kicker is that only Blizzard could tell you if the item was properly implemented. The truth is possibly lost to time.

**Comment by ratkosrb** [comment]
```
Most seals were calculated client-side on the initialization of the swing...
```

What did I just read? :rofl:
Nothing is calculated client side, only thing that is controlled by client is movement of your character. Everything else you do in the game is just a request to the server. The client just tells the server you want to begin auto attacking a given target, and then the server decides if that's allowed, when each attack goes off, what damage it did, and what procced from each attack. The client has no control over when your character actually swings at the target.

The only reason seal twisting was possible was because of the delay added to SoC in 1.11, that's what made it possible, since the decision whether this seal procced or not happened at a different time than all the other seals. That allowed you to benefit from both SoC and another seal if you switched seals at the right moment. How would that possibly have worked with a different rank of SoC, they both have the same delay on triggering, and thus there is no way for the race condition which enables twisting SoC with other seals to actually happen.

```
I'm not gonna beg here for it to be added into vmangos core because 100% SoC is indeed not vanilla. But if anything qualifies as the "push this button to fix this entire class", it is undoubtedly this. I do not say this lightly; it doesn't feel like a gimmick at all, which is what most "paladin tricks" feel like. The 100% proc reward for correct twisting was the most satisfying and "paladin-esque" dps rotation I have seen in 17 years of wow, including WotLK. And it was all because of a one-line mistake.
```

It is completely irrelevant if a bug was fun, it is not a blizzlike bug, and therefore has no place in the emulator. This is not a private server, this is an emulator, we are not trying to provide the most fun experience for players, we just try to reproduce the behavior of the original servers, no matter how un-fun it was in given situations. Do not bring up enjoyment of the game when arguing for a given behavior, as that only undermines your point. It shows you just want whatever is more fun to you, and don't actually know or care if this behavior is accurate for Vanilla.

And you have yet to provide any actual evidence that twisting 2 ranks of SoC was possible in Vanilla. The Classic PTR is not a valid example on this topic, as it was clearly stated by Blizzard that what you have there is a custom re-implementation of seals to make them linger for 500ms after being replaced by another seal, since spell batching is being removed. That is merely a workaround to allow you to proc two seals at the same time, but it's not how it worked in Vanilla or TBC, seals never lingered there. What allowed you to proc both SoC and another seal was the delayed batch window on SoC, which they added so it can benefit from Vengeance.

And in fact, Classic actually indicated the opposite of what you are arguing for, because on the live servers we do have actual spell batching, and twisting 2 ranks of Seal of Command is not possible. That debunks your whole theory right there. It's seals being made to linger that allows double SoC twisting to happen.

Either post a legit video of somebody doing that during original Vanilla, or bring attention to this PTR interaction on the official forums and hope that Blizzard notices and actually confirms this behavior is consistent with the 1.12 reference client in a blue post.

**Comment by Velite12** [comment]
I have to agree with ratkosrb. Ultimately if you can't demonstrate that this behavior existed prior to the PTR seal stacking on classic then it wouldn't be possible to recreate this behavior since it can't be proven that it was "vanilla". It has to be 1.12.1 or prior behavior, and SoC twisting is the only concrete one that can be proven.

**Comment by YellowRyder** [comment]
> What did I just read? rofl
Nothing is calculated client side, only thing that is controlled by client is movement of your character. Everything else you do in the game is just a request to the server. The client just tells the server you want to begin auto attacking a given target, and then the server decides if that's allowed, when each attack goes off, what damage it did, and what procced from each attack. The client has no control over when your character actually swings at the target.

This is what generally what I said, though I misspoke when I said "most seals were calculated client side". What I had meant is that when the player applies a seal/buff, the process is initialized client side and then processed server side. The delay during this communication is where seal twisting happens, as evidenced by the fact that the only recorded information on vanilla seal twisting was people being able to twist SoC into SoJ. I believe this happened because both of these seals required the server to process the procs by referencing a table and then making a roll, whereas every other seal was considered static and could be calculated immediately upon the client's combat initialization request being OK'ed by the server.

Obviously I don't have the vanilla source code here to point this out (no one does), but this is a logical conclusion as to why only proc-based seals could be twisted and why they could only be twisted from Seal of Command - due to the additional batching delay on top of the additional cycle required to roll for procs.

I don't agree with Ratkosb. I said multiple times that I'm not requesting anything be added to vmangos that is unblizzlike. On the contrary, I want to see the twist mechanic refined to be as vanilla as possible. To imply that I'm here to convince you otherwise is dishonest; I never advocated for seal twisting to be in vmangos originally because any attempt to re-create it is by default not vanilla. I view it no differently than artificial batching or leeway.

And just because I don't have a video or forum post from 2005 describing how to increase PPM of SoC by using a technical flaw to trick the game server doesn't mean it didn't exist. I can't attest that it existed personally as I didn't play the game during this time. But from a logical standpoint it would make sense. What do I know, I'm a nobody who is simply rehashing the information that I spent a whole night sorting through in an effort to better improve the vmangos project.

**Comment by ulfgebhardt** [comment]
This discussion is very good in my opinion, but is turning into an argument bit by bit while I do not find evidence that different goals are pursued. Therefore I would ask all participating parties to work together and figure out if a change is needed and if so how to implement it. Lets keep it constructive <3 (Suggestion: everyone goes on hunt for evidence and post your findings here)

Furthermore I want to thank @YellowRyder for doing the effort of making the graphics above and explaining how it works in such detail. Thank you!

And as a side note to all you "as-accurate-as-possible-emulator-evangelists": With the new plans of blizzard to have rolling server patches and eternal servers for each version we all agree that custom servers will be the go to thing in the future. So it is in our interest to support "fun features" as log as they are turned off by default, since it will increase the reach of our software and therefore our available developers. And yes I know - servers can modify the code and make it fun, but if a custom server can stay close to the original source chances of getting their blizzlike fixes (and custom content) are better. (pls don't discuss this here, we can do that in another thread)

**Comment by YellowRyder** [comment]
I fully agree. I am not here to be combative towards anyone, but to simply share the findings I have come across. I am by no means a programmer, not an expert of mangos. But I have a familiar enough understanding of structuring and a fundamental grasp of how the processes function in a server/client state. Most of my experience comes from java based game, which often are handled entirely server side.

The fact that there was a delay implemented to SoC for the explicit purposes of increasing the damage throughput shows that the true spirit of the vanilla system was to give players a reward on the attack by slightly delaying the SoC proc damage in order to facilitate activation of the vengeance talent. This was done in 1.11 and it's when seal twisting was first "created". The only evidence of seals being twistable was with SoC and SoJ, both of which were the only two proc-based seals in the game (again, light and wisdom were originally static hit modifiers that were removed and re-added later). This leads me to believe that the client's request to initialize combat and the server's reception and processing of this request which in turn began the attack sequence is where the magic is. Every seal besides SoC and SoJ would be issued on the same batch as the combat initiation response from the server; The proc based seals required a roll on a table which added one clock cycle. On top of this, one additional batch was added to SoC in 1.11 which is how you were able to twist SoC into SoJ (and later SoB during TBC). We can logically assume that Seal of Command had some sort of mechanic artificially added at this point which gave it a "delay"; but since only SoJ (and later SoB) were calculated after the sequence initiation, they were the only seals able to be twisted.

If this here is true, then it would also stand to reason that multiple ranks of SoC functioned the same way; They would have an inherent delay due to the roll required, not including the added additional delay. Twisting two ranks of SoC would trick the server into processing two rolls for SoC after the attack initiation sequence, simply due to the added delay in 1.11. This would not cause two instances of SoC damage, but simply a double roll on the table; If the first one hit it would trigger ICD - a built in feature to prevent reckoning from proccing SoC multiple times.

https://www.youtube.com/watch?v=bi0_bSfNctY

Here is a video of Seal of Justice in retail classic wow. Watch the first couple of minutes. Notice how the proc activates AFTER the swing has taken place? This is different that mangos; In mangos, the SoJ stun proc activates immediately upon initiation of the swing. This is what I spoke of in regards to original vanilla combat initiation and attack sequence being different than vmangos. White hits in vanilla were calculated one cycle after the swing initiation sequence; This is likely due to the cycle required to roll the attack table, and the batching window which was originally in game. Some times your hits would "appear instantly", other times they would be delayed by a couple hundred MS; This was entirely dependent on the batching window.

This is why Seal twisting didn't work on private servers until it was artificially added as well; Private server with batching didn't have seal twisting because of the way mangos handles combat sequencing. Without the added cycle delay for proc-based attacks, you cannot achieve this effect without doing it artificially as Ratkosb did. His work in adding the seal twisting mechanic was genius, but fails to accurately simulate twisting because of the inherent flaws in mangos.

I think what we really need to discover is the exact mechanical change made in 1.11 that initially caused seal twisting.

**Comment by punker85** [comment]
https://github.com/the-hyjal-project/bugtracker/issues/333

My thoughts at the end of that should give a better picture of how it worked. Spell batching really has no benefit to this mechanic since these are self casted buffs. However, when u activate a seal, there is a possibility that the original server software just did not have proper logic to instantly cancel old seals as soon as the new seal packet is received. Consider that seal spell packet is sent by the client at time 0 but server is already preparing to send attack update packet to client in 100ms cuz swing timer is almost 0. Then, the attack update packet ends up being calculated when the server is receiving the seal spell packet in the 0 to 100 interval but probably attack packet is sent to client before the old seal aura gets cleansed from players buff record. Mangos clients seem to perform many calcs and operations synchronously with a minimum required thread model.  Vanilla servers used a more asynchronous model with lots of delayed processing and possibly some actual thread management. 
Also, there was no 100% proc from this mechanic in any twisting video that ive seen.

**Comment by YellowRyder** [comment]
> Consider that seal spell packet is sent by the client at time 0 but server is already preparing to send attack update packet to client in 100ms cuz swing timer is almost 0. Then, the attack update packet ends up being calculated when the server is receiving the seal spell packet in the 0 to 100 interval but probably attack packet is sent to client before the old seal aura gets cleansed from players buff record.

This was my exact assumption. I believe that seal twisting has almost nothing to do with batching - and everything to do with the delay between client/server. The process of applying a seal is initialized by the client, reported to the server and then returned with the result; but somewhere in this process is the inherent delay that is resultant from latency, batching, and clock speeds of both client and server.

> Mangos clients seem to perform many calcs and operations synchronously with a minimum required thread model. Vanilla servers used a more asynchronous model with lots of delayed processing and possibly some actual thread management.

This is evidenced with how Seal of Justice functions in the real vanilla and retail classic clients - the stun effect is applied when the damage goes off, but in mangos it procs immediately upon swing. I firmly believe that these two factors are the reason seal twisting never existed on private servers, even those with a level of batching. In true vanilla, twisting wasn't discovered until after 1.11 when the extra delay was added to seal of command; and even then, people found that it could only be twisted with seal of justice. I firmly believe that this was during a period of time where no one was truly theorycrafting these mechanics, that seal twisting was very undisclosed and underreported in the community and no one realized exactly what was happening; People assumed it was a strange fluke. It was not utilized until TBC with Seal of Blood; This new seal was the third amongst Justice and Command to share a proc-based mechanic which had to get rolled from a table. Don't forget that although Light and Wisdom are actually static in terms of scripting, Justice is not - there were talents to modify the PPM at one point in the game, which would have affected a tabled roll. This extra cycle needed in computing to perform a roll is necessary as the compute functions cannot be done at the exact same time that the process is called, unlike static information which can be transmitted back immediately next cycle.

Mangos eliminates this with modern design standards, better software and much better hardware than the original vanilla wow ran on. This is an inherent flaw which will always separate mangos from real vanilla: Unless it is the exact same code running on the exact same hardware with the exact same latency, there will always be a difference. And that brings me to this point:

> Also, there was no 100% proc from this mechanic in any twisting video that ive seen.

Yes. As I have stated from the beginning, 100% proc on twist is not vanilla.

But it brings up the issue that I had originally tried to address: The current seal twisting mechanic in mangos is not vanilla either. It is fun, it is intuitive, it is brilliantly designed in a simple yet effective way; But it is not vanilla. The real vanilla seal twist was only documented to function with Command being twisted to Justice. This again goes back to the issue of how mangos is inherently different from true vanilla. The proc from Justice is not vanilla as it is currently scripted because it doesn't have the inherent delay that was required to process the tabled roll which the vanilla Justice had. To simulate this in vmangos, we would need to do the exact same thing which was done to Command during original vanilla, by adding an artificial delay (ala Patch 1.11). If this was done, it was stand to reason that the delay should be shorter than Command, but longer than any other seal except Seal of Blood. For sake of argument we could say that the delay for Justice and Blood should be 0.25 seconds, with Command being its current 0.5 as referenced with the custom aura.

This is the reason seal twisting only explicitly worked from Command to Justice (and subsequently Blood) - because with Justice or Blood the delay in which the proc is rolled takes one extra cycle, with Command having an additional (patch 1.11) cycle delay. It is because there is a sequencing to all of this, and the check for this roll would have had to happen after the sequence was initiated. The artificial delay added to Command was what created the problem; When a new seal was swapped that required a roll check, the server would then process it despite the attack sequence having been initiated. This would lead me to believe that the server preemptively calculated a check state on the client/player, as shown in the first figure of my initial post. This check state information is used for the sequence initiation (player location, direction, buffs, stats, etc.), but when the client throws a new change in between the sequence initiation check and the roll checks, the server will assume that both are active; It would require an additional cycle to adjust this.

This is where the proc for Justice, Command and Blood is integral. When the attack sequence initiates, the server checks the table of information for the player. Let's say for example, we had Seal of Righteousness active. We would initiate attack sequence, the table would be referenced, the attack would be rolled and the damage would occur. With Seal of Righteousness, the damage occurs before the white hit due to the calculation for damage being instant - there is no random roll involved in this, outside of the attack roll itself which is done during the beginning of the initiation sequence. The combat sequence would appear to the player as this:

1.) Initiate attack
2.) Swing
3.) Yellow hit from Righteousness
4.) White hit

With a seal that is proc-based such as Justice or Blood, it should require one additional cycle - delaying the proc to time alongside the white hit, like so:

1.) Initiate attack
2.) Swing
3.) A short delay in which nothing happens
4.) White hit and Justice proc

However, this does not happen on vmangos. Justice procs during step two, at the end of the initialization sequence and the beginning of the Swing sequence. There is clearly an effect of batching on this, as show in classic client; The proc on mangos happens immediately upon the server giving the green light for the attack initiation. However, this means that it is doubly incorrect; not just from lack of batching, but from the proc roll occurring too early in the sequence. This is the real reason why it was totally impossible to twist Command and Justice on mangos.

With Command having an artificial delay added with patch 1.11, the sequence appears as follows:

1.) Initiate attack
2.) Swing
3.) A short delay in which nothing happens
4.) White hit
5.) Command proc

This again reaffirms my belief that in true vanilla, the additional delay added to Command was causing an interaction specifically with all seals which required a tabled roll to be checked; the additional cycle required to roll the proc, coupled with technical limitations, created a strange phenomenon in which players were able "trick" the server into checking for two seals. This couldn't have occurred with any non-proc based seals, because the server issued a calculation preemptively from the table during packet preparation before the Attack Initiation Sequence had even occurred - as no roll was required. It was really just a programming trick to free up resources that was causing this. The preemptively prepared packet which contained the information about the active seal was being rolled alongside with a newly twisted seal. The server may or may not have "removed the buff", but the roll was still issued on the table and placed into the stack.

I'd bet $5 that this isn't really an issue of "seals lingering" at all - but of a "replaced seal" being rolled for on the table preemptively, and triggered during the roll sequence of the new proc-based seal. The server sequencing and delay clearly had some factor in this, but I'd guess it was many issues. It can essentially be thought of in a similar way to buffer overflow in computing, or how defense cap works in WoW. By having Command retain an extra delay, the sequencing would appear as follows:

0.) Seal of Command is triggered to be removed by the client and replaced with Seal of Justice
1.) Initiate attack -----------------------------Seal of Command is batched into the attack sequence already as a time saver
2.) Swing -------------------------------------Calculations are made before this happens, Seal of Justice is active
3.) Seal of Justice proc is rolled by the server during this short time between swing calculations and the hit appearing
4.) White hit, Seal of Justice Proc, Seal of Command proc

This is exactly how the mechanic functioned in true vanilla, in terms of sequencing. This leads me to believe that when the swing calculations are made, the server is flagged to roll on a table for a proc. It checks which procs need to get rolled, sees Seal of Justice AND Seal of Command needing to get rolled during this exact same cycle, and does so. If not for the additional cycle delay that was added in patch 1.11, the server would discard this roll after a new check state was issued. But because the seal was removed but the roll lingered on the table and was sequenced for the same time as the roll for Justice, both get rolled at the same time. This was also true with Seal of Blood, as it shared the same cycle delay timing as Seal of Justice did for the required roll.

If this is indeed the case, it would logically follow that a twist between two ranks of Seal of Command would cause the server to prepare the attack sequence packet with the one rank issued, and then get forced to roll it alongside with a different rank of Seal of Command. Since Command has an internal cooldown, it could not proc twice in one swing; But logic would dictate that the same delay which caused twisting would indeed cause two ranks of Command to be rolled on, effectively doubling the proc rate.

This may seem unrelated, but it exactly the issue we are experiencing but shown in a different fashion:
https://www.youtube.com/watch?v=gz4HzuZ8Cs8

In this video, Rextroy demonstrates how simply swapping between two weapons with correct timing will facilitate Seal of Righteousness to use the previous weapon's damage on the preemptively issued packet which was drawn from the current check state. When the combat sequence is initiated, you are able to swap weapons and with careful timing you can receive the full damage benefit of the previously equipped weapon on Seal of Righteousness while having the benefit of the newly equipped weapon's speed. This is only partially due to batching, but also partially due to how the true vanilla system was using a bag of cheap tricks to save time and resources without computing everything synchronously. It would just do everything which required a check in advance, and update it with each new cycle. This not-in-time form of processing is rudimentary by many standards, but it allowed programmers to accomplish great things with limited technology. 

I think that this was one of many things which was simply unknown at the time. No one bothered trying to carefully time twists of different ranks of seal of command during this time period. It wasn't until around Naxx when this was discovered, and no one was using ret paladins in any serious fashion. What we really need to do is figure out exactly what Blizzard did in patch 1.11 to change Command which subsequently lead to twisting. I am limited in my knowledge of how mangos works, so I hope this massive wall of text simply helps as food for thought. Maybe I'm totally wrong about everything.

**Comment by ratkosrb** [comment]
Being able to twist 2 ranks of SoC was removed before 1.13.7 went live, so confirmed this was unintended. And you can only twist with SoC and another seal. However twisting things with SoC did not work at any point in Classic while batching existed, so there's still no evidence of it being a thing in Vanilla. We now have a more accurate recreation of spell batching in the core, and it allows for all the different interactions i know of in Classic while batching was in the game. For example swapping weapons between swings with SoR does work. I consider this topic closed.
