### ISSUE TITLE
🐞 [Bug]SFK Arugal's Voidwalkers encounter

### ISSUE THREAD

**Issue by Agney-gt** [vmangos/core#1247]
## 🐞 Bug report - Spell

-- What Quest/NPC/Loottable/Gameobject/Event/Spell is bugged?
https://classic.wowhead.com/npc=4627/arugals-voidwalker#abilities;mode:normal

--Current Behaviour: Does not use its ability "Dark offering"

### Expected behavior

Should use its ability "Dark offering" as seen in this youtube video.

https://user-images.githubusercontent.com/84612798/123232553-e55c3200-d4f6-11eb-8165-64d85c8cf2ec.mp4

### Steps to reproduce

1. Kill fernis the devourer
2. Watch the 4 voidwalkers spawn
3. Kill them 1 by 1 without use of the spell where the low hp mob takes some hp from another voidwalker and increases its own hp
4. The voidwalkers should keep healing the low hp one by sacrificing some of their hp.
5. Profit

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  

OS Client:  Win 10
OS Server: 

### Crashlog

- None

**Comment by mserajnik** [comment]
You should add the commit hash to the issues you create so it's automatically documented in which commit something didn't work and when it got fixed (especially important years from now when someone wants to look it up; e.g., if some regression breaks it).

**Comment by T1ti** [comment]
https://classic.wowhead.com/spell=7154/dark-offering this is the spell

**Comment by Agney-gt** [comment]
Hi,  im playing on a private server, i apologize for being unable to provide the commit hash data.

**Comment by GrenderG** [comment]
> Hi, im playing on a private server, i apologize for being unable to provide the commit hash data.

What private server? How do you know they are using an up to date VMaNGOS core / they haven't done any custom changes that might affect this behavior?

**Comment by NickTyrer** [comment]
![Untitled](https://user-images.githubusercontent.com/22723839/123419711-7512e680-d5b2-11eb-85f3-19ad296a766b.png)
DId you test on vmangos? According to the eventai they have this ability. If you are only testing on the pserver please review all of your bug reports by testing on the latest revision of vmangos.

**Comment by mserajnik** [comment]
> Hi, im playing on a private server, i apologize for being unable to provide the commit hash data.

Was it Darrowshire? I saw that server mentioned in [one of your other issues](https://github.com/vmangos/core/issues/1237). 

According to [this post](https://www.reddit.com/r/wowservers/comments/m6wzu0/some_fun_facts_about_the_new_darrowshire_project/), they are not using VMaNGOS, but instead the older Light's Hope code as a base.

Of course, I can't verify if everything that Reddit post claims is true, so I won't comment any further on that.

But if they are not publishing their modified source code to their users (which you imply by saying that you are unable to provide the commit hash, because if they did, you could just look it up in the code), they appear to be knowingly exploiting the [GPL SaaS loophole](https://www.whitesourcesoftware.com/resources/blog/the-saas-loophole-in-gpl-open-source-licenses/), which to me personally would make them leeches trying to piggyback off of other people's work without contributing back.

Sorry for the off-topic comment, but it had to be said.

---

I also agree with what NickTyrer has stated: before opening an issue, you should always check if it hasn't already been fixed in the latest version/commit, or you'll cause unnecessary work for the maintainers/contributors trying to replicate the problem. And that goes for any project, not just VMaNGOS.

**Comment by Agney-gt** [comment]
Im sorry for this error on my part, I asked the owner and he said that they are using VMaNGOS with numerous changes including removing honor decay and some kind of anti-botting system. They provided me with this hash number - 5dd6f8b4603361a4f49163e110cfdf2d8614b7d6. 

Also, they have implemented some changes from vMaNGOS in their server recently - 03.06.2021 
(- corrected alot of wrong spell IDs in creature spell lists - VMangos
- fixed bosses respawning after their adds successfully wiped the raid - VMangos
- - added missing ore veins spawns - VMangos)

I hope this info would be sufficient to get a better idea on weather the darrowshire team are piggybacking off your work.
