### ISSUE TITLE
🐞 [Bug] Divine Shield - Not Protecting From Drowning Damage

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1504]
## 🐞 Bug report - Spell
When the paladin activates the ability "Divine Shield" while drowning, it doesn't protect the paladin from damage caused by drowning.

### Expected behavior
The paladin shouldn't take any damage while drowning.

Commit Hash: 10ea1cc

**Comment by ratkosrb** [comment]
Have you tested this on classic? Could you provide a video.

**Comment by NickTyrer** [comment]
https://youtu.be/tLUOfY8m5I0

**Comment by ghost** [comment]
I was able to fix this by making 2 adjustments to Player::EnvironmentalDamage:
1) call CalculateDamageAbsorbAndResist for drowning type (similar to lava, etc.)
2) do not send packet if damage is reduced to zero for drowning type (otherwise player will see absorb message, which does not seem to reflect blizzlike behavior, based on the video)

![Preview](https://user-images.githubusercontent.com/22320709/169294760-4c474bef-8a34-4253-8911-0a138956237a.PNG)

I can make a pull request if needed. I'm still fairly new to MaNGOS codebase, so let me know if there's a better way / place to fix this.

Btw, it might be worth testing how this interacts with some other types of absorbs as well (priest shield, etc.) and whether the absorb message can be seen on client for different environment damage types (when damage is reduced to 0).

**Comment by ratkosrb** [comment]
I was actually planning on fixing that but I forgot.
