### ISSUE TITLE
🦂 [Bug] C'Thun (Phase 2) NPC

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1518]
## 🦂 Bug report - Dungeon

After killing the _Eye of C'Thun_, in the beginning of phase 2, when _C'Thun_ summons a tentacle under my feet in order to transport me to _C'Thun's Stomach_, this does not happen. Instead I instantly die, resetting the whole encounter (solo play).
### Expected behavior

Well this should normally work as expected. I remember years ago I am properly transported to _C'Thun's Stomach_ when playing in **TrinityCore** (_WoTLK_).
### Steps to reproduce

1. Do the _Temple of Ahn'Qiraj_ raid normally as a solo player (buff yourself with custom items or GM commands).
2. When fighting _C'Thun_ check for this problem.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
2c0854594e85a738751f4aa8b7a5a696b55e7ebe

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by Daribon** [comment]
The example you used is from another emulator, it should not be used as an example of expected behavior. 

Until patch 5.1.0 Mist of Pandaria you couldn't solo C'thun. Because if there was no players on top fighting C'thun it would assume the raid had wiped and then insta kill everyone in stomach.
> [Patch 5.1.0](https://wowpedia.fandom.com/wiki/Patch_5.1.0) (2012-11-27): Players now have 5 minutes to escape C'Thun's stomach and resume the battle before it resets.

The current behaviour on vmangos is blizzlike. This case can be closed.
