### ISSUE TITLE
🐝 [Bug] The drop rate of Shadow Hunter Knife for quest:691 should be corrected

### ISSUE THREAD

**Issue by den13501** [vmangos/core#1652]
## 🐝 Bug report - Quest

I did quest 691:Worth Its Weight in Gold about 4 hours, killed many witherbark shadow hunters, but they never droped the item:5040
and I check creature_loot_template, the ChanceOrQuestChance is -20, but I saw drop rate from wowhead should be 23.30%
### Expected behavior

refer to wowhead
https://www.wowhead.com/classic/quest=691/worth-its-weight-in-gold#comments
https://www.wowhead.com/classic/npc=2557/witherbark-shadow-hunter
https://www.wowhead.com/classic/item=5040/shadow-hunter-knife
### Steps to reproduce

check creature_loot_template, the drop rate of this item is -20
![image](https://user-images.githubusercontent.com/58270741/195975498-3aa67c46-b48f-4a47-bda2-4b8207d1bdf1.png)

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630

**Comment by mserajnik** [comment]
@NickTyrer

~~Is this fixed? I can't spot anything relating to it in https://github.com/vmangos/core/commit/6eb7e54c7008e11d3661809961403c7011bd440a (and also in the remaining unmerged changes from #1970); although it's very early here, so maybe I'm just blind. 😄~~

Turns out I am blind since you referenced #1630 here and not #1970; I think I got confused because of the same PR title.

But it looks like this got addressed [here](https://github.com/vmangos/core/commit/cbf9cd95ca86d27f721681d0084d55f1057748da#diff-fa8449b336dbb842bbfc6e6f6b3783242d56f253342b4435e26d85d979ff2dd0R432) so this issue can probably be closed?

**Comment by ShiyoKozuki** [comment]
The drop rate is not 23% on Classic Era, it's more like 5%.
Quest drops on here overall are extremely generous compared to Classic Era
Sadly, I think it's impossible to get accurate data on this without botting leveling characters to test.

**Comment by ratkosrb** [comment]
You two are saying contradictory things. Come to a decision. Should it be 23% or 5% ? It can't be both...

**Comment by mserajnik** [comment]
Wowhead doesn't factor in if an item is only dropped when you are on a quest, so the displayed drop rate for such an item can be heavily skewed if the mob in question is frequently killed and looted without being on that quest (while using the Wowhead client).

That said, in practice that should mean that displayed drop rates for quest items on Wowhead are generally too low compared to what they actually are.

**Comment by ratkosrb** [comment]
@ShiyoKozuki Do you accept @mserajnik's argument?

**Comment by mserajnik** [comment]
@ratkosrb Seems like you are enjoying yourself here. 😆

In all seriousness, I am not arguing that Wowhead drop rates are accurate; I am not arguing anything at all I guess. I just looked through the issues, saw this one had a comment, got curious and clicked on it and noticed that Nick supposedly fixed it but probably forgot to close it, which is why I pinged him.

If @ShiyoKozuki can show that 23% is too high and it should be lower then that's fine by me too. 🙃

**Comment by ShiyoKozuki** [comment]
I can't show it. It requires too much testing and data to prove drop rates.
I just know from personal experience of doing quests on Classic Era and doing quests here, the drop rates are much more generous(higher) by a pretty big amount on this project. Some are actually lower than Classic Era, though, like the Ashenvale water elemental bracelets.
Generally, quests drops for multiple items felt they were were ~20%(1 in 5).
Rarer 1 off drops like the knife from this quest felt like ~5% (1 in 20).
Stuff like this knife or dew laden gland were generally a ~30-60m grind on Classic Era while being something you got within 3 kills or so on here.
This drop specifically was around 5% from doing it multiple times on Classic Era.
It's practically impossible to prove this, though.

My opinion doesn't really matter though, and it's up to the owner's of the project and how they want to handle the drop rate. I am just giving my personal experience with this project after having played it and Classic Era.
