### ISSUE TITLE
🐛 [Bug] "Air Bubbles" Buff (underwater breathing) not working in Forgotten Pools and Stagnant Oasis

### ISSUE THREAD

**Issue by wolffsi** [vmangos/core#1663]
-->
## 🐛 Bug report
When swimming over the spring/source being inside the Air Bubbles (Forgotten Pools + Stagnant Oasis) no "Air Bubbles" Buff gained, thus no underwater breathing.
Picture (only Forgotten Pools)
https://drive.google.com/file/d/1jYmjX4OATS-4Q4YOmfUNNcUjUtzp5PAW/view?usp=sharing

### Expected behavior
When swimming inside the spring/source you get Air Bubbles Buff like in Lushwater Oasis
https://drive.google.com/file/d/1a1CFkQfARhKvgWA0Z4PEXzKo9_MEsx7B/view?usp=sharing

### Steps to reproduce
Go dive in either Forgotten Pools + Stagnant Oasis

**Comment by FlagFlayer** [comment]
@wolffsi You're going to need to make those drive links able to be viewed by anyone. Currently they are not viewable.

**Comment by wolffsi** [comment]
sorry, should work now

**Comment by Florian-2023** [comment]
I came here to report this, but I see that it has already been reported, but no-one is assigned to it.
I would not mind to try to fix this, if someone could spare the time to get me up and running.
Or give me a tip on where to start. 
I understand that one can only do so much, therefore I like to offer some help instead of complaining.
