### ISSUE TITLE
🚀 [Feature] New command for .partybot

### ISSUE THREAD

**Issue by xBarselonx** [vmangos/core#1794]
## 🚀 Feature
Hi!

Please consider adding commands for tanks. For example, it would look like this - .partybot pull. 

This command works only for tank - .partybot pull [target boss, mob]
This command only works on the tank. All other bots (healers and dps) do nothing until they receive the command .partybot attackstart.

### Benefits, Purpose

This command will allow the tanks to better aggro mobs or boss, because when you use the command .partybot attackstart attack begin all the bots and damage rdd ahead of the damage of the tank.

**Comment by mserajnik** [comment]
For reference, NycterMoon (which I believe bases its companion AI at least partially on the default VMaNGOS party bots) has implemented such a command: https://web.archive.org/web/20231007160913/http://nyctermoon.wikidot.com/zcommands#toc10

Note the optional arguments `duration` (defines how long the DPS are paused) and `back` (causes the tanks to attack and then run back to the player, useful for corner pulling) which seem like useful additions.

**Comment by gajet5** [comment]
Made here:: https://github.com/vmangos/core/commit/9a0dc9a723f80f427275d23b1f0462c5ab452d65

**Comment by mserajnik** [comment]
> Made here:: [9a0dc9a](https://github.com/vmangos/core/commit/9a0dc9a723f80f427275d23b1f0462c5ab452d65)

That commit of mine was only a first draft/attempt and is completely untested; feel free to try/use it, but I have no idea if it works (hence why I didn’t make a PR).

**Comment by gajet5** [comment]
The logic looks good. I'll try it on my server.

**Comment by mserajnik** [comment]
I was trying to replicate the functionality of the command on NycterMoon (as linked above) but I didn't manage to implement the `back` parameter (I couldn't figure out how to make the tank hit a mob once and then automatically run back to the player).

**Comment by gajet5** [comment]
He doesn't seem to have such an option in the description. There is an option to return after a while.
But if I were doing this, I would be looking at a change in the level of aggression.
pTarget->GetThreatManager().getThreat(pPlayer)
Initially, it is 0, if there was a blow, then it is no longer zero and bot can run to the player.

**Comment by mserajnik** [comment]
> He doesn't seem to have such an option in the description. There is an option to return after a while.

I think the duration only affects the pause; iirc, I saw a video that explained the bots and there he used this command and the tank came back immediately after hitting the mob once.

> But if I were doing this, I would be looking at a change in the level of aggression.
pTarget->GetThreatManager().getThreat(pPlayer)
> Initially, it is 0, if there was a blow, then it is no longer zero and bot can run to the player.

That does sound reasonable; the main road block I hit with this is that there doesn't seem to be a way to script bot behavior based on future events (e.g., be able to set up a callback that's executed once the bot acquires aggro) because just blocking further execution with a `(while aggro == 0)` loop (pseudo-code) doesn't seem ideal.

But thinking of it again, I guess the "simple way" to go about this is to have some flag that indicates when a tank is pulling (e.g., `m_isPulling`) which is then checked in `PartyBotAI::UpdateAI()`; if the aggro is zero, we return early, once it goes above zero (or the bot gets a new command in the meantime) the flag gets cleared (and the rest of the method is executed as necessary).

I might take a look at this again later today.

**Comment by gajet5** [comment]
Based on the description of the command, it can be concluded that only time affects. As for irc, it seems to me that it has other, heavily redesigned bots. At least that's what I saw in the source code.

Is your idea for the bot to run to the player on impact to install the boss at the point?

It seems to me that this can be done with the "cometome" command, it doesn't make sense in the "pull" command.

Since you will have to do the redundant logic of ignoring the combat mode.

**Comment by mserajnik** [comment]
> Based on the description of the command, it can be concluded that only time affects.

~~I would have to look up the video again, but he specifically used it for corner pulling in SM in the video; I could misremember.~~

__Edit:__ I found the video: https://youtu.be/pEp1pBpi_rI?si=zrjliHwWT7mxPOQp&t=1220

It's not clear from the video if the `back` parameter triggers upon first hit on the mob or a specific time, because in the video he uses `comestay` after the tank has pulled aggro to manually bring him back. So it could well be that only the specified duration affects the `back` parameter as you say.

Also, the video shows Stratholme, not SM (as I wrote before).

> As for irc, it seems to me that it has other, heavily redesigned bots. At least that's what I saw in the source code.

Are you talking about NycterMoon? I haven't seen the source code because I didn't think that's available anywhere (I faintly remember the developer saying on Reddit that he won't make it public); if it is, I would be very curious to see it. But maybe I misunderstood what you meant. 

> Is your idea for the bot to run to the player on impact to install the boss at the point?

It would be mostly useful for trash pack corner pulling, I think (like in the video I mentioned).

> It seems to me that this can be done with the "cometome" command, it doesn't make sense in the "pull" command.

Yeah, maybe it would be better to just use a macro for this and combine the two commands when necessary; I did have a brief look yesterday and you are right, implementing this would cause a lot of redundancy with all the checks in `PartyBotAI::UpdateAI()`.

**Comment by mserajnik** [comment]
> The logic looks good. I'll try it on my server.

I was able to test it myself now and it seems to work as expected; I will make a PR as is, without the `back` parameter as I think just using a macro for that (or calling the tanks back manually when needed) is the simpler and better solution, at least until it gets possible to code this in a nice way via event listeners.

The only thing I am not sure about is that the duration has to be set in milliseconds, but I did that so it's consistent with the `.partybot pause` command (which also requires you to enter the duration in milliseconds); I will highlight that in my PR, it's a quick change if necessary.

**Comment by gajet5** [comment]
Sorry. I misunderstood. I meant these bots. 
https://github.com/ike3/mangosbot

I think that your fast performance is what is needed. it seems to me that there is no need to be too clever with a simple command.

If you do something like setting the boss to the point. then you need to prescribe the tactics of the raid. I'm trying to do something like that right now.

**Comment by gajet5** [comment]
> > The logic looks good. I'll try it on my server.
> 
> I was able to test it myself now and it seems to work as expected; I will make a PR as is, without the `back` parameter as I think just using a macro for that (or calling the tanks back manually when needed) is the simpler and better solution, at least until it gets possible to code this in a nice way via event listeners.
> 
> The only thing I am not sure about is that the duration has to be set in milliseconds, but I did that so it's consistent with the `.partybot pause` command (which also requires you to enter the duration in milliseconds); I will highlight that in my PR, it's a quick change if necessary.

Microseconds are not convenient for most people. I have plans to change for myself all the places where microseconds meet for seconds.
