### ISSUE TITLE
🐝 [Bug]Freed from the Hive - missing pre 1.7(?) version

### ISSUE THREAD

**Issue by Gamemechanicwow** [vmangos/core#1802]
## 🐝 Bug report - Quest

https://www.wowhead.com/classic/quest=4265/freed-from-the-hive 

Quest was an escort during earlier patches - Not entirely sure when it was changed but comments suggest it was with patch 1.7.

### Expected behavior

https://web.archive.org/web/20050103134056/http://wow.allakhazam.com/db/quest.html?wquest=4265

Accepting the quest prior to patch 1.7(?) should start an escort.

### Version & Environment

Client Version: 

Commit Hash:  1042d2d6dff037acab55

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Daribon** [comment]
I thought it was weird myself while I was leveling since the quest complete was so delayed.

I can confirm that it used to be an escort quest just by looking at broadcast text.
His first text, entry 4949:
('Oh man, I thought I was dead for sure.  Ugh... still dizzy...', '', 4949, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
His second text, entry 10620:
('I can get back to the Stronghold on my own, I think.  Now that you bought me some time, I should be able to stealth out of here.  Who ever you are... thank you.  May Elune bless you always!', '', 10620, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),

Broadcast text entry 10620 has Arathi Basin and ZG text entries around it.

**Comment by mserajnik** [comment]
The escort quest apparently has a different name too: `Escaping the Hive` (versus the non-escort quest that replaces it, `Freed from the Hive`). But the quest ID stays the same, `4265`.

And a comment [here](https://classicdb.ch/?quest=4135) (can't put a link that jumps  to the comment directly since the comments markup is built from JSON when the page loads) suggests that there was a bug where no NPC appeared upon accepting the quest:
<img width="1147" alt="image" src="https://github.com/vmangos/core/assets/80664890/bfd9ca6d-e527-4900-b6e3-6f6e1b5f12cf">

And another comment [here](https://web.archive.org/web/20080303193045/http://thottbot.com/v538143) also mentions it being bugged, although they state that it was changed in 1.8, not 1.7 (as other comments suggest):
<img width="650" alt="image" src="https://github.com/vmangos/core/assets/80664890/a08ec02b-b258-4d29-8a47-5cb2255d3c08">

Based on that last comment it sounds like the escort quest might have never worked correctly and Blizzard decided to just remove it (instead of fixing it).

**Comment by ShiyoKozuki** [comment]
On classic it works like it does here, no escort.
