### ISSUE TITLE
🐛 [Bug] first migration date

### ISSUE THREAD

**Issue by burner1024** [vmangos/core#2147]
## 🐛 Bug report
- [Last](https://github.com/brotalnia/database) database dump from the repo linked in the wiki is from 2021.06.14.
- First migration [here](https://github.com/vmangos/core/tree/development/sql/migrations) is from 2021.05.15.
- Next migration is from 2021.06.15.

Is the first migration unnecessary? Then why is it the repo?
Or is it a typo, and it's actually from 2021.06.15 too?

### Expected behavior
Only necessary migrations in the repo.

**Comment by codestothestars** [comment]
The date in the migration file name is the date on which the migration was created, not when it was merged into the repository. If you look at the file's history and the associated pull request, it was merged on 2021.06.20, quite clearly after the latest database release. So no, there isn't an issue here.

**Comment by burner1024** [comment]
Uhm, what does it matter when it was merged? The content of the files in a pull request doesn't change with date.
Still not clear what's the answer to the original question.

**Comment by codestothestars** [comment]
It matters because that means one thing happened before another. 

* Database release created on 2021.06.14. 
* Migration merged on 2021.06.20

Given that sequence of events, the database release couldn't possibly include this migration because the migration wasn't in the repository at the time, so it is now still in the repository. The date in the file name is essentially irrelevant except to give a vague idea of when the change occurred, and to give it a unique name.

**Comment by burner1024** [comment]
But how do you create a migration for a database that is not released yet?

**Comment by codestothestars** [comment]
There is essentially an assumption that the database will not change in a way that conflicts with the migration between when the migration is created and when it is merged. Of course this is not guaranteed, and if a conflict does occur then it is soon corrected. The same principle applies to the database release, because the database release simply represents the cumulative state of migrations at that point in time.

**Comment by burner1024** [comment]
OK, so just to be clear, all migrations including  20210515110157_world.sql are supposed to be applied onto world_full_14_june_2021.7z, right?

**Comment by codestothestars** [comment]
That's correct.
