### ISSUE TITLE
Issue with explosives of Covert Ops - Apha and Beta quests

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#222]
**Current behavior**: NG-5 Explosives(Blue) always fail when you try to use them in the wagon (guid 47494) and NG-5 Explosives(Red) for wagon with guid 47605 for the next quest in chain (1080).

**Expected behavior**: The explosives should be placed correctly in order to lure the enemies and use the detonator after that.

**Steps to reproduce**:

1. Take the quests (1079 and 1080) and try to place the explosives.

**Comment by ratkosrb** [comment]
I need a retail video of how the quest should work. Can you record it on the classic beta?

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=Kx8pSK7ZlWw
https://www.youtube.com/watch?v=GSl1tx0s1Io

They are from classic beta apparently

**Comment by ratkosrb** [comment]
No, they are not. This is private server footage. The videos were uploaded a week before the beta was even announced, and the bug report pop-up is not there. Also he does not even use the bombs provided for the quest, but instead just kills the mobs guarding the quest item. Can you guess why he does that? Because it's not scripted on the private server he is playing.

**Comment by ghost** [comment]
I see, we need someone with access then

**Comment by GrenderG** [comment]
Here you go, this channel has more quests from beta, very useful:

https://www.youtube.com/watch?v=XenYBxrB_EM
https://www.youtube.com/watch?v=XohhDItp7Xs
