### ISSUE TITLE
🐛 [Bug]Event PVP Silithus Cannot be turned on automatically

### ISSUE THREAD

**Issue by zxnhrdz** [vmangos/core#2259]
Event 103
 Events are automatically turned on by default
 Default on time 2020-09-08 12:00:00-2030-12-31 11:00:00
 Not refreshing Silithyst Mound and Silithyst Geyser

  Client Version:
  - 1.12.1.5875
  
  Commit Hash:
  017c2625e113954119336df6e707cfe4bf66029a

  Operating System:
  Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-166-generic x86_64)

**Comment by Wall-core** [comment]
Did you enable silithus pvp in your config file? Also some events require you to manually start them, like AQ event phases.

**Comment by zxnhrdz** [comment]
![image](https://github.com/vmangos/core/assets/110412571/d651a078-be61-4ea6-987f-ab310c14f0e3)
It's on by default and the configuration file doesn't need to be moved.

![image](https://github.com/vmangos/core/assets/110412571/b3099985-2671-4ebe-b561-8454bf993fe8)
The database is also turned on by default, but does not take effect.   game_event 103

**Comment by mserajnik** [comment]
~~Unless I am mistaken, there appears to be an issue with the name of the config options; they are called `OutdoorPvp.SIEnabled` and `OutdoorPvp.EPEnabled` in the config file: https://github.com/vmangos/core/blob/b5d1c07474e5eec7ae1993f7c01e2eb44b318b58/src/mangosd/mangosd.conf.dist.in#L2676-L2687~~

~~However, in the code it's looked for `OutdoorPvP.EP.Enable` and `OutdoorPvP.SI.Enable` respectively: https://github.com/vmangos/core/blob/b5d1c07474e5eec7ae1993f7c01e2eb44b318b58/src/game/World.cpp#L791-L792~~

~~That bug was introduced in https://github.com/vmangos/core/commit/dce57fee270eb7a08a609ecb4a6e69d85b0ee27a, over 5 years ago where the options were renamed in the config file but not in the code reading them.~~

__Edit:__ I just noticed that it defaults to `true` when the config options can't be found, so that's probably not the issue here (but rather a separate, smaller bug).

__Edit 2:__ The config issue is fixed in https://github.com/vmangos/core/commit/13c43993b5095d1c759cc174586417994b5fb776.
