### ISSUE TITLE
🐛 [Bug]Minus armor but not actually any armor minus (Display bug?)

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2345]
## 🐛 Bug report
Defense had -armor but my armorwasn't actually lowered at all.
Not sure what caused it. Relogging removed it.
The 2 armor difference after relogging is due to changing a belt that gave me 2 less armor.
Before and after relogging my armor didn't actually change, this is simply a weird display bug.

### Expected behavior

Shouldn't have -armor for no reason
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 
  - 1.12.1.5875

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None
![image](https://github.com/vmangos/core/assets/58101246/b3ca70b5-29af-4356-8fa6-b266b0e65bcd)
![image](https://github.com/vmangos/core/assets/58101246/724b374b-d5da-4945-af0f-b118e8b8622e)

**Comment by Wall-core** [comment]
Delete your WDB. Has nothing to do with the core.

**Comment by ShiyoKozuki** [comment]
> Delete your WDB. Has nothing to do with the core.

Relogging fixed it. Why is it WDB related? The stat screen said I had red(minus) armor but didn't.
None of my items were custom at the time of this bug.

**Comment by Bdunk17** [comment]
Because core deals with the raw values and those don’t change in your two pictures. Most of the UI Lua files are located in the WDB folder so that’s how you know it’s in there. The files in that folder use the wow api functions and event handlers to locally record data from the core. Your client then uses that data to render a visual representation of the game. In this case your UI probably had a bug which caused it to miss an aura removal event which it was listening for. Since that event was never captured that frame is probably just sitting there waiting for that combat log event to trigger the change from red. Hope that makes sense because I spent way too much trying to explain it.

**Comment by ShiyoKozuki** [comment]
Thanks.

**Comment by gajet5** [comment]
Hmm I have this error to and I use two version client. 1.12.1 and 1.14.0 with proxy. This error happened after bos fight. Version don't emit event sounds like possible.

**Comment by Bdunk17** [comment]
@gajet5 More than likely are dealing with an event handler that never triggers possible due to the events not lining up between the two versions. The color change function is probably registered by a couple events events find out which one is not picking if you want answers.
