### ISSUE TITLE
🦂 [Bug]Uldaman bugs / polish

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2368]
## 🦂 Bug report - Dungeon
https://www.wowhead.com/classic/quest=2201/find-the-gems containers have a long respawn timer, this is a quest item everyone in your party has to loot.

Obsidian Sentinel doesn't have spell reflect.

Bots get stuck at this spot:
![image](https://github.com/vmangos/core/assets/58101246/49b076e0-9730-4807-8101-e55750c057d8)

### Expected behavior
https://youtu.be/ZDKVY15GTJk?t=2665
https://www.wowhead.com/classic/quest=2201/find-the-gems containers should respawn within a few seconds.
Obsidian Sentinel should have spell reflect - https://www.wowhead.com/classic/npc=7023/obsidian-sentinel#comments

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server: win10

**Comment by GoonBoiBarry** [comment]
> Revelosh does not drop the The Shaft of Tsol 100% of the time. This blocks you from completing the quest "The Hidden Chamber" unless you reset and reclear. Group loot, bots with 2 players.

This is again, mostly like because you are using bots with group loot. Bots do not loot their share and you will sometimes miss important items like this if you do not change the loot sharing settings.

> https://www.wowhead.com/classic/quest=2201/find-the-gems containers have a long respawn timer, this is a quest item everyone in your party has to loot.

This is not necessarily an issue. If it was like that in vanilla, then it is functioning correctly. Unless you are saying it is not functioning like vanilla, there is no reason to mention it as a bug.

**Comment by ShiyoKozuki** [comment]
https://youtu.be/ZDKVY15GTJk?t=2665
Essentially every single quest container that's a single loot to finish (noble brew, fuel regulator, etc) respawns within seconds or never despawns at all on Classic.

**Comment by NickTyrer** [comment]
Closed here #1970
