### ISSUE TITLE
🐛 [Bug]Respeccing should unlearn the ranks of that talent and not give them back for free

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2408]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/88ae9199-7673-4193-be23-8224c6a9a408)
![image](https://github.com/vmangos/core/assets/58101246/60b40dfd-8fb5-4667-8bf1-eb57aaaaa61b)

Spec into a talented ability that has additional ranks, like holy shield. Learn all ranks.  Reset talents, which properly deletes all the spells ranks, then spec into holy shield again, you don't have to rebuy holy shield ranks, they're automatically re-learned.

### Expected behavior
You should have to rebuy holy shield ranks besides rank1.

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by MarcelineVQ** [comment]
I can't think of a reason this would benefit the experience of playing the game.

**Comment by ShiyoKozuki** [comment]
> I can't think of a reason this would benefit the experience of playing the game.

https://github.com/vmangos/core

Accuracy: The point of an emulator is to recreate the functionality of that which it is emulating as closely as possible. Therefore any custom behaviour should be behind a config option and off by default.

**Comment by ratkosrb** [comment]
You didn't post any proof it should work this way.

**Comment by mserajnik** [comment]
Hm, this is an interesting one. I can't find too much information about this (and certainly no definitive truth).

There is a bigger discussion about this in [this Reddit thread](https://www.reddit.com/r/classicwow/comments/dutncj/does_unlearning_specspecific_talents_require_you/?rdt=56462). Reddit is obviously not a reliable source, but the interesting thing here is that there are a lot of conflicting statements with people seemingly experiencing different things.

Here are some of most the relevant things said:

> Surprisingly nobody is getting it right in this thread. You only have to re-learn the spell ranks if you don't re-learn the spell right away.

> [in reply to the previous statement] That doesn't seem right, either. If I had to guess, the actual differentiator is likely whether or not you relog after resetting talents.

> From reading the thread, it might be class specific. Or maybe even only applies to certain abilities. I respec 2x a week on my warrior between prot and arms and i have to relearn ranks 2-4 of shield slam or mortal strike every time.

> In vanilla it depended on class, that's just how it was, so that's why you such different answers

> They [presumably Blizzard?] said that in vanilla you had to retrain them, but in classic (#nochanges my ass) you automatically get all ranks back

> if when you respec you are learning same spells that your previous spec had you dont have to relearn ranks. So if you learn shield slam and respec and learn it again you don't have to learn them again. But if you have shield slam spec into arms and spec back to prot you need to relearn the shield slam ranks

>This is incorrect. That's how it worked in Vanilla, but in Classic you just get all your ranks back instead of wasting the extra ~80-100s.
>
>Edit: Apparently none of us are correct, and all of us are correct. It seems some people do need to retrain spell ranks in one class/spec or another at some times. I have respecced eight times now and have never once retrained my tree-specific spells, but another Priest is telling me he has to do just that. So idk.

There is also [this thread](https://us.forums.blizzard.com/en/wow/t/respecing-now-grants-all-ranks-of-talented-spells/585106) in the official forums where someone claims this was changed (so you don't have to re-learn spell ranks) in some patch in Classic, although I also couldn't find it in the patch notes:

> I don’t believe this is “undocumented.” The change was documented in official patch notes for Classic months ago.

[Here](https://us.forums.blizzard.com/en/wow/t/rebuying-skills/305809/9) and [here](https://us.forums.blizzard.com/en/wow/t/respec-rebuy-talents/397543) are also two Hunter players complaining about having to re-learn ranks; those predate the previous thread which also talked about Trueshot so it seems likely this was (at least in Classic) changed at some point:

> Eveytime I respec I am having to rebuy trueshot Aura from the trainer. Pretty simple bug but very annoying.

> I went to respec tonight and was surprised to learn that I had to rebuy all ranks above rank 1 Trueshot and Aimed shot.

In the the first thead there is also this interesting remark (which links to [this Wowhead thread](https://ptr.wowhead.com/forums&topic=27613), although there isn't much additional info there because sadly most of the comments were deleted and there is no archived version in the Wayback Machine):

> People were even confused about this in 2009 and folks remember having to re-buy skills: https: //ptr. wowhead com/forums&topic=27613
>
> I didn’t play much past AQ so if this was changed sometime in Vanilla near the end I wouldn’t know. I do remember the early days having to relearn abilities, as do others as evidenced by this post from 10 years ago.
>
> If it’s not in 1.12 then it’s not in 1.12. I’m sure one of you edgelords can look at patch notes. I found more folks bugging about it through google searches from 2008 and prior so have fun!

**Comment by ShiyoKozuki** [comment]
> You didn't post any proof it should work this way.

Do you have retail access? It would cost me $15 to test this.

**Comment by GoonBoiBarry** [comment]
Just tested it on classic era 
![image](https://github.com/vmangos/core/assets/146424299/cea50a0c-8f79-491c-aa9e-1bc74e38c278)
Can't really prove it from an image, but it automatically relearned holy nova ranks when I talented it at no cost or input. Not a bug.

**Comment by ShiyoKozuki** [comment]
Interesting, this was changed in some version of Vanilla, then. They have a much lower cost because originally you had to re-buy them.
