### ISSUE TITLE
🦂 [Bug]Lord Alexei Barov immolate 

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2463]
## 🦂 Bug report - Dungeon
Initial hits for 771
Ticks for 405
Targets any party member with it.

### Expected behavior
Initial should hit for ~500
Should tick for ~140
Only targetted the tank with it
https://youtu.be/ej5Y4tAQ0zI?t=4666

**Comment by GoonBoiBarry** [comment]
You can see later in the video when immolate wears off that the 67 ticks appear to be from his dot aura and not the immolate. It also looks like the immolate hits for 480 when he reapplies it later. You may still be right that numbers are off, but I would guess something like this would not be changed without a sniff or a full combat logged video because of spell resist

**Comment by ShiyoKozuki** [comment]
> You can see later in the video when immolate wears off that the 67 ticks appear to be from his dot aura and not the immolate. It also looks like the immolate hits for 480 when he reapplies it later. You may still be right that numbers are off, but I would guess something like this would not be changed without a sniff or a full combat logged video because of spell resist

Exact time for 140 tick:
https://youtu.be/ej5Y4tAQ0zI?t=4727

**Comment by GoonBoiBarry** [comment]
You had different numbers intially, but yeah that's probably right. Again, it's hard to know if it's a resist or not without floating text or combat log, so probably not verifiable. In my experience, this stuff only gets changed with sniffs, so I don't bother reporting damage anymore
