### ISSUE TITLE
Missing fail chance on interrupts

### ISSUE THREAD

**Issue by GuybrushGit** [vmangos/core#249]
> Patch 0.6:  [Kick]. It now has a 75% of working, similar to other interrupts.

Its either an added miss chance to the regular miss formula or a second roll on EffectInterruptCast.
If its a second roll then Kick would still do damage while the interrupt fails, needs to be tested on classic.

**Comment by ulfgebhardt** [comment]
We need more info on this @GuybrushGit - what are your findings? Can you link us more  resources on this? <3

**Comment by punker85** [comment]
In patch 0.7, the probability was changed to 100%.

**Comment by ulfgebhardt** [comment]
@punker85 Does this mean the current implementation is correct or do you refer to version 1.7?

**Comment by punker85** [comment]
> @punker85 Does this mean the current implementation is correct or do you refer to version 1.7?

It means that the change that the OP references from beta patch 0.6 was reverted a few months later in the next beta patch. One could assume that the reasoning behind this was due to complaints from testers in the beta phase. I would hope that this project is not trying to recreate concepts that were tested and adjusted during beta implementations.

The added miss chance for interrupts was implemented in beta due to player complaints. Then, it was removed due to other player complaints.

**Comment by ratkosrb** [comment]
Thanks for clearing this up. We are only trying to emulate 1.2 to 1.12, so this is not applicable to us.
