### ISSUE TITLE
🐛 [Bug] vmangos and vrealmd on Ubuntu 24.04 wont start: libACE-7.0.6.so missing

### ISSUE THREAD

**Issue by latchee** [vmangos/core#2824]
## 🐛 Bug report

Hi there,

After upgrading Ubuntu from 22.04 to 24.04, libACE-7.0.6.so is removed and libACE-7.1.2.so is installed instead. This prevents either vmangos and realmd from starting:
> vmangos/bin/realmd: error while loading shared libraries: libACE-7.0.6.so: cannot open shared object file: No such file or directory

I was able to work around this issue by installing libACE-7.0.6.so from Ubuntu 22.04's repository: http://archive.ubuntu.com/ubuntu/pool/universe/a/ace/libace-7.0.6_7.0.6+dfsg-2_amd64.deb
(https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/libace-7.0.6_7.0.6+dfsg-2_amd64.deb.html)

I first tried to do a symlink of libACE-7.1.2.so to libACE-7.0.6.so but it resulted in this error:
> vmangos/bin/realmd: symbol lookup error: vmangos/bin/realmd: undefined symbol: _ZN14ACE_Ini_ImpExpD1Ev
So, from my point of view, it seems that vmangos is not compatible with libACE-7.1.2.so

**Comment by ratkosrb** [comment]
You can compile the [native branch](https://github.com/vmangos/core/tree/native) instead to avoid this issue.

**Comment by mserajnik** [comment]
`libace-7.1.2` works just fine, but you need to recompile VMaNGOS after upgrading from Ubuntu 22.04 to 24.04 to build against and link to the updated version of ACE (with `libace-dev` installed during compilation for the headers).

So, install `libace-dev`, recompile VMaNGOS, and then you can remove `libace-dev` again and install `libace-7.1.2` instead (since you don’t need the headers for running VMaNGOS). Or, which is probably easier if you will want to recompile VMaNGOS often, just keep `libace-dev` installed, then you also don’t need to explicitly have `libace-7.1.2` installed (since it’s a dependency of `libace-dev` anyway).

You can check out my [Docker setup](https://github.com/mserajnik/vmangos-deploy), specifically the [Dockerfile for the server](https://github.com/mserajnik/vmangos-deploy/blob/master/docker/server/Dockerfile), to see how to compile on Ubuntu 24.04. I use a multi-stage build where I first install all the required `*-dev` packages for compiling and then in the final stage instead install the regular library packages (to reduce the size of the Docker image by not including the headers); so that's essentially what I described above (with installing and then uninstalling `libace-dev` again after building). But yeah, if you are not using Docker and instead build directly on a machine, I would just keep `libace-dev` installed to keep things simpler (as mentioned before).

**Comment by latchee** [comment]
Hi there,

Thank you @mserajnik and @ratkosrb , I have tried to build the core with libace-dev on branch development, I get this error:

> CMake Error at CMakeLists.txt:95 (message):
>   This project requires ACE installed.  Please download the ACE Micro Release
>   Kit from http://download.dre.vanderbilt.edu/ and install it.  If this
>   script didn't find ACE and it was correctly installed please set ACE_ROOT
>   to the correct path.

I can confirm than ACE_ROOT is configured:

> $ echo $ACE_ROOT
> /usr/include/ace

While on the branch native, I was able to build after deleting the build folder and creating it blank again.

Thank you both for your help !
