### ISSUE TITLE
How to add a custom script?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#48]
How to add a custom script?
I want to add a custom NPC and use the menu options to achieve the functionality I want. . .

**Comment by ratkosrb** [comment]
You need to say more details about what you want to achieve. Do you mean a script assigned to a gossip option? That is easy to do, you just assign the script id from `gossip_scripts` to the `action_script_id` column of `gossip_menu_option`.

**Comment by DarkmoonRabbit** [comment]
I want to achieve the goal: add an NPC, a menu appears after talking to the NPC, click menus print "Hello world" in the chat box.
I want to learn how to add custom features, don't know if you can help me, give me a demo.(^_^)

**Comment by ratkosrb** [comment]
First you need to add the text.
```
INSERT INTO `broadcast_text` (`ID`, `MaleText`, `FemaleText`) VALUES (99900, 'Hello world', 'Hello world');
```

Then you need to make a gossip menu. For menu ID we choose 17000 because its free.
```
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES (17000, 1);
```

Then you need to add a gossip menu option for players to click.
```
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_script_id`) VALUES (17000, 1, 'click me', 1, 1, -1, 33333);
```

Now we add a script with id 33333 which we have assigned to the gossip option. You can use the Script Editor to create scripts.
```
INSERT INTO `gossip_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES (33333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99900, 0, 0, 0, 0, 0, 0, 0, 0, 'example script - say hello world');
```

And finally you need to assign the gossip menu to a creature. For this example I choose npc 197 (Marshal McBride) who is the quest giver in the human starting zone.
```
UPDATE `creature_template` SET `gossip_menu_id`=17000, `npcflag`=1 WHERE `entry`=197;
```

Here i also update `npcflag` to 1 which enables gossip. Without it you can't talk to the npc.

**Comment by DarkmoonRabbit** [comment]
Don't need any C++ code?

**Comment by ratkosrb** [comment]
Nope.

**Comment by DarkmoonRabbit** [comment]
@ratkosrb THKs. :-)

**Comment by DarkmoonRabbit** [comment]
hey @ratkosrb brother! Thank you for your previous teaching!
I want to know the following, can I trigger a custom script for CPP files when I click on the menu? I see this location is a custom script area, can you teach, give me a skeleton script
Https://github.com/vmangos/core/tree/development/src/scripts/custom
