### ISSUE TITLE
Multiple issues in Rend fight (UBRS).

### ISSUE THREAD

**Issue by blipblopium** [vmangos/core#557]
This fight is really bad scripted at this moment, the code is really messy and might even lead to bugs like the entire fight resetting.

Also, there are many issues like Gyth yelling, instead of Rend, or lack of events like Nefarius moving around or the spectators appearing and cheering.

cmangos has this fight perfectly working, so it might be useful to take a look at their implementation.

**Comment by blipblopium** [comment]
Actually it might be useful to rewrite a lot of PvE encounters taking a look at cmangos implementation, they recently reworked a lot of them.

**Comment by GrenderG** [comment]
I have indeed wanted to fix this fight since a long time, so far these are the current issues I noticed:

- Players not being removed from combat between waves.
- Event not resetting after a wipe, bugging it (doesn't always happen).
- Gyth yelling instead of Rend.
- Rend not spawned near Nefarius.
- Missing movement of Nefarius and Rend during the event.
- Missing spectators cheering on the left balcony (should spawn on event start and despawn on combat end, and must not be selectable).

So yeah, I'm pretty sure this is one of the most incomplete and buggy PvE encounters at this moment. As @blipblopium said cmangos has it working, but structure is so different that it might be worth to start fixing it from scratch or taking our current script as a base.

As a side note, there's also a mini event that is missing here (cmangos has it too) when players reach The Beast boss room.
