### ISSUE TITLE
[EVENT] Southshore Crier

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#599]
**Current behavior**: 
Currently this event is partly implemented, however I am not sure how it is triggered i.e by completing a quest or a timed event. The event should spawn Shadowy Assassin which drop the quest item Assassin's Contract.

**Expected behavior**: 
I havent been able to see the event in classic so I am unsure of the details however there is some information in the following forums:
 - https://classic.wowhead.com/npc=2435/southshore-crier#comments
 - https://classic.wowhead.com/npc=2434/shadowy-assassin#comments:id=2842005

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by Gamemechanicwow** [comment]
Not sure how accurate this is. But could be useful - there is alot of detective work compiled here:
https://vanilla-twinhead.twinstar.cz/?issue=5124

**Comment by Daribon** [comment]
I've done Assassin's Contract on classic.
From what I experienced, two stealthed shadow assassins spawned near me and then started attacking me. Killed one of them and looted the quest. I never noticed anything about Soutshore crier.

**Comment by ulfgebhardt** [comment]
From the link @Gamemechanicwow provided:

The event is missing.
http://www.wowwiki.com/Southshore_Crier

1) Southshore Crier should spawn on the road fork just north of Southshore.
- He spawns on a specific server-time, exactly at 5 AM and 5 PM.
Proofs:
http://www.wowhead.com/npc=2434/shadowy-assassin#comments:id=951155
http://www.wowhead.com/npc=2434/shadowy-assassin#comments:id=594555

2) Along with him, several Shadowy Assasins spawn, comments do not give precise number, but according to the comments it seems 8 in total at once.
- They should always spawn in pairs, one male assasin and one female assasin
Proof: http://www.wowhead.com/npc=2434/shadowy-assassin#comments:id=683332 (and the comment below it)

The Shadowy Assasins should be in STEALTH. If a player passes nearby, they will aggro as any hostile NPC.

Their spawn location is random and spans the whole Southshore city. They can spawn:
- In the Town Hall entrance
- In the Inn entrace
- In the Stables
- In any other building's entrance
- Behind the Town Hall
- Near the river
- Directly on Magistrate Henry Caleb
- One pair of assasins should ALWAYS spawn in the middle of the city, because that's where the Southshore Crier is headed.
See wowhead comments for their multiple spawn locations.

3) When the NPCs are spawned, a dialogue starts:
- Southshore Crier yells: Help me! Help! Assassins in the hills! To arms! To arms!
Now he should run from the north road fork to the middle of Southshore.

As he passes the Flight Master, he continues:
Southshore Crier says: Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!

But when he reaches the middle of the city:
Southshore Crier grabs the back of his neck and his eyes go wide.
Southshore Crier says: Assassins... save... th... Magistraaa...

Crier dies and all the assasins now should move towards the Town Hall, getting aggroed by guards, NPCs and players. At this moment:
Magistrate Henry Maleb says: More agents of the Syndicate I'll wager! You'll never take back Alterac... or Southshore!

Source: http://www.wowhead.com/npc=2434/shadowy-assassin#comments

**Comment by LEO33SoFo** [comment]
Bump.

**Comment by LEO33SoFo** [comment]
Issue still exists as of c8cef536eb7af0c2bab9d945d9e974fcfa7d63b9 (bump).

**Comment by Oroxzy** [comment]
Will be added soon i guess, we sniffed it.

**Comment by LEO33SoFo** [comment]
Any progress?

**Comment by Daribon** [comment]
Aight so I checked on som and sniffed parts of it.
Appears that they spawn in several locations away from the village with random movement, then on some trigger they will activate waypoints and walk into the village to attack civilians, guards cannot detect them until they go out of stealth.
