### ISSUE TITLE
[< 1.2] Why not?

### ISSUE THREAD

**Issue by ghost** [vmangos/core#640]
Why don't you plan to add support for versions 1.0 and 1.1?

---

I have no access to Discord, they're flagging me immediately and I don't want to give my phone number to them.

**Comment by Daribon** [comment]
1.0 was never a release version, 1.0 is US beta.
1.1 was never a release version, 1.1 is still US beta.
1.1.1 was the release version of WoW.
1.1.2 was only out for less than a month until 1.2 came, this makes it hard to find information 1.1.2.
Another thing to note is that 1.1.2 was only released in US, 1.1.2 was EU beta. Release client for EU is 1.2.0

It gets increasingly harder to find data about a patch the longer you go back in time.
I would also like to point out that 1.2.0 was the first major patch, which included content which was not finished in time for the CD disks, such as Maraudon. 

Had Blizzard had more time before shipping the CD disks, we probably would have had Maraudon in 1.1.2. We know this, because Maraudon has NPC entries in the range of Molten Core, which implies that it was under development during about the same time.

Hope this gives you some insight why 1.1.2 is not supported.

**Comment by Gamemechanicwow** [comment]
Another thing to note is that some of the early clients also had performance issues and bugs.

**Comment by ratkosrb** [comment]
Daribon summarized it pretty well. Another reason is that I started the progression system during the Elysium times, and that server launched from 1.2 (content wise), so it was picked as the starting point of progression. Adding support for older patches now would require updating all patch values used everywhere in db and core. Once we have support for all clients including 1.2.4, I might add compatibility with 1.1 client in a separate branch just for fun, but only 1.2.4 to 1.12.3 will be officially supported by vmangos.
