### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by ghost** [vmangos/core#647]
What is the proper way to update VMaNGOS? Updates are frequent and I cannot wait almost an hour to rebuild it.

If I add SQL migrations, mangosd lists them as extra ones.

**Comment by GrenderG** [comment]
This is not an issue. Please use the Discord for this kind of doubts.

**Comment by ratkosrb** [comment]
A sane compiler will only recompile files that have changed. You can use "git pull" to update your local source with the latest changes. The extra migrations warning is not an issue, its just a notification. It is there for your benefit, so that you know you have migrations newer than the core. The list of migrations is created when you configure with CMake.

**Comment by ghost** [comment]
> This is not an issue. Please use the Discord for this kind of doubts.

Discord does not allow me to join. They are flagging me immediately and I will not give my phone number to them. I did not use any proxies and they think I'm a spammer.

If there is a way to bypass phone verification, let me know.

**Comment by ghost** [comment]
> A sane compiler will only recompile files that have changed. You can use "git pull" to update your local source with the latest changes. The extra migrations warning is not an issue, its just a notification. It is there for your benefit, so that you know you have migrations newer than the core. The list of migrations is created when you configure with CMake.

Do I have to rebuild it (all files) if I want to change supported version?
