### ISSUE TITLE
Bloodfang Hood and Chestpiece Wrong Models

### ISSUE THREAD

**Issue by mnemonic-re** [vmangos/core#666]
**Current behavior**: 

Bloodfang Hood and Chestpiece don't have their originial model. Hood is some red stuff and chest is some orange thing.

**Expected behavior**: 

They should be cool :)

**Steps to reproduce**:

1. Roll a rogue
2. Spawn the items
3. See the character

**Client version**: 

1.12.5875

**Commit hash**: 

**Operating system**: 

Win

**Comment by Gamemechanicwow** [comment]
If you have set wowpatch in the servers configfile to pre 1.9 - you will get the old t2 models.

https://www.reddit.com/r/wow/comments/4mmhjb/this_is_what_tier_2_looked_like_before_aq_was/

If your wowpatch is set to 1.9 or later and you still see the old models, i would advise you to delete your clients wdb folder. Thats a cache folder and can contain old or corrupted data.

A little heads up.. Where Blizzards Classic phases are mostly just gatekeepers for content, and itemstats are static 1.12 values - changing a patch in vmangos also reflects items that had their itemstats changed during vanilla patches.
Another example besides the t2 models.. The AQ items you can get from turning in scarabs and idols in cenarion hold was buffed in 1.11. If you set vmangos to patch 1.9 you will get the old unbuffed items, as they where during vanilla 1.9 - but on classic you will get the item as it where during patch 1.12.
So.. if you are trying to use vmangos as a classic ptr server, you would want to use 1.12 so you get the same itemstats as on classic.

**Comment by ratkosrb** [comment]
I think you have content patch set to 1.2 (wowpatch = 0) in mangosd.conf, and are unfamiliar with the original models for the tier sets. This is a progressive project, and items change depending on the content patch you've chosen to simulate in the config.

https://imgur.com/r/wowservers/HcFjZ

If you want to have the updated models, then set the wowpatch setting to 7 or higher. And remember to delete your WDB folder in order to see the change. The client caches all items info, and once you've seen an item, no subsequent server side changes will be visible until you delete the cache.

**Comment by mnemonic-re** [comment]
WowPatch = 10 in my config?

**Comment by mnemonic-re** [comment]
WowPatch = 10 in my config now and still models wrong?

**Comment by Gamemechanicwow** [comment]
>And remember to delete your WDB folder in order to see the change. The client caches all items info, and once you've seen an item, no subsequent server side changes will be visible until you delete the cache.

**Comment by mnemonic-re** [comment]
I never changed the WoWPatch. It was always 10. But I will do that.

If you have time, try Patch 10 and see.

**Comment by mnemonic-re** [comment]
Clearing cache fixed the problem! Thanks!
