### ISSUE TITLE
Disable non-blizzlike Russian locale by default

### ISSUE THREAD

**Issue by ghost** [vmangos/core#684]
There is no official Russian locale for vanilla WoW, but VMaNGOS supports unofficial one (most likely [this](https://wowruru.github.io/)).

It should be disabled by default as non-blizzlike.

**Comment by ratkosrb** [comment]
There is no such thing as "disabling a locale". If you don't want to have russian locales then delete them from the db yourself. Logging in with the custom Russian client is already blocked by default because of the strict version checking functionality in realmd. And by the way our localized text data comes from Classic, it is not from any fan project.
