### ISSUE TITLE
Banning addons

### ISSUE THREAD

**Issue by ghost** [vmangos/core#720]
**Current behavior**: Banning addons not implemented

**Expected behavior**: Banning addons should be implemented. See TrinityCore implementation ([1](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Addons/AddonMgr.cpp), [2](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Server/WorldSession.cpp#L1158)).

**Client version**: unknown but not older than 1.6.1

**Comment by shagu** [comment]
As far as I understood, this mechanism is used to validate builtin blizzard addons like "Blizzard_CombatLog" and such. 
Since 2.x-TBC there's a secure mechanism that prevents user created addons from accessing several things. 
Blizzard Addons on the other hand, are signed and allowed to do everything.

As far as I understood, the linked mechanism is used to validate the blizzard addons and if a change is detected, the addon gets disabled by the server.

However, Since there is no secure-addon mechanism in Vanilla at all, I doubt that the client can even handle those request.

It's also not required to modify a blizzard-signed code since every addon is already allowed to do anything.
And even if the client could handle it, it's fairly easy to rename your addon to get out of the ban-list again.

I'm not a sever-dev, but from my point of view, it doesn't make any logical sense for vanilla-clients.
