### ISSUE TITLE
what this?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#78]
FindScriptTargets: Failed to find buddy for script with id 6 (target_param1: 2532), (target_param2: 30), (target_type: 8).

**Comment by alexkulya** [comment]
William (Entry: 2533) when driving on Waypoints uses scripts ID 6 & 7 in which the action of the script takes place on the NPC ID: 2532 (Radius 30 Yards). The error happens when NPC 2532 dies or not detected within the specified radius, the solution to the problem can be adding the condition to perform the action only if present in the radius of NPC (2532).

**Comment by ratkosrb** [comment]
This is not really a problem. The error in the console happens because there are no players nearby, so the grid search for the other npc fails since its not loaded.
