### ISSUE TITLE
[Item] Movement Boosting Items

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#831]
**Current behavior**: 
There should be a 5 min cooldown between the use of items such as Nifty Stopwatch and Rocket Boots see:
https://wowwiki.fandom.com/wiki/Goblin_Rocket_Boots
https://classicdb.ch/?item=2820#comments
note: this needs to be tested in classic to confirm

**Client version**: 
1.12.1
**Commit hash**: 
3d73832
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Where do you suggest the cooldown should be set, because the cooldown in item_template comes from ItemSparse.db2 and ItemEffect.db2, and you do not doubt client files. No changes to the 1.12 version of items that deviates from the client files is permitted. And according to our current data, the shared cooldown between them was removed in patch 1.11. They used to both have spellcategory = 28 and spellcategorycooldown = 300000. There was a rework of all item cooldowns in this patch.

Quote from the 1.11 patch notes:
```
- We have re-evaluated the mechanics of consumable items in the game 
  and concluded that these should work in a more intuitive manner. As 
  such, most items that can not be equipped with right click abilities 
  have been streamlined into one of three categories. Using an item of 
  a particular category will trigger a shared cooldown among all other 
  items in the same category. The categories break down as follows with
  category cooldowns as listed.
   Potions 2 minutes: This includes items such as Health Potion, Mana 
   Potion, Invisibility Potion and Mighty Rage Potion.
   Aggressive 1 minute: This includes items such as explosives, Really 
   Sticky Glue and Discombobulator Ray.
   Non-Aggresive 2 minutes: This includes items such as Healthstone, 
   Night Dragon's Breath, Whipper Root Tuber and Target Dummy. 
- Many items that can be equipped have had their cooldown category 
  removed and will be controlled exclusively by the item's self 
  cooldown. For example, the Gnomish Mind Control Cap should no longer 
  trigger the cooldown of the Talisman of Arathor.
```

If you look on the item history page on allahkazam, you can see the initial category cooldown they had, which matches what we have for pre 1.11.
https://web.archive.org/web/20050416043120/http://wow.allakhazam.com/db/itemhistory.html?witem=2820
https://web.archive.org/web/20060328180746/http://wow.allakhazam.com/db/itemhistory.html?witem=10724

But now look at the client db files of classic.
https://wow.tools/dbc/?dbc=itemeffect&build=1.13.0.28211#page=1&search=2820
https://wow.tools/dbc/?dbc=itemeffect&build=1.13.0.28211#page=1&search=10724

As you can see there is no category cooldown, only individual cooldown on the item. Exactly as in vmangos db.

**Comment by NickTyrer** [comment]
Cheers for looking into this. Will close, as working as intended.
