### ISSUE TITLE
[NPC] Galak Messenger - waypoints

### ISSUE THREAD

**Issue by schell244** [vmangos/core#861]
Galak Messenger seems to have some waypoint issues. 
Within his path the npc walks through walls/map borders.

https://classic.wowhead.com/npc=10617/galak-messenger

**Client version**: 
1.12.1
**Commit hash**: 
ff17826
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
I remember this being a mmap issue. Only way around it would be to make a super detailed path for him that would not require pathfinding. He could then move in a straight line from point to point, avoiding the bugged sections of the mmaps. To do this, waypoints from `creature_movement_special` would have to be loaded from his AI script. It's more of a hack though, the real issue is with the mmaps, which I can't fix.

**Comment by schell244** [comment]
Ok I see. Would be interessting to know if this issue also occurs with CMangos code. Once I've tested this, I'll update this ticket.

**Comment by schell244** [comment]
Update: mmap issue does not occur on latest cmangos classic code (48cb423)

**Comment by ulfgebhardt** [comment]
@schell244 could you link the relevant commits so we have a chance to port it? <3

**Comment by schell244** [comment]
CMangos waypoints are identical to VMangos waypoints. 
(https://github.com/cmangos/classic-db/commit/e2f99999a4ec3ca6e0ad9c2016882308ebd8bd51)

Issues seems to be due to vmangos mmaps, like @ratkosrb already mentioned. There's no single commit which I could link here  becasue I also don't know where the issue is coming from.
I guess the first steps for approaching this issue (for someone who's not experienced with mmaps code) would be comparing all the mmap related code (from extractors to how mmaps are processed) and any small change within mmaps would probaly require a lot of testing.

Maybe we should open a [vmangos mmap issues] ticked, where we could link/gather all pathing issues due to mmaps. So if there are any mmaps changes in future, we know more places where to check the results.

**Comment by ulfgebhardt** [comment]
I like the idea with the issue! I will do that in given time.
-> I think a problem might be the resolution of the mmaps - cmangos allows to extract high resolution mmaps and vmangos does not. If you look how the behavior is you will notice that mobs run over the peaks / prioritize the uneven terrain... but thats just a wild guess

**Comment by Gamemechanicwow** [comment]
Problem found.

The issue is that the mmap generator thinks the area below the bridge is under terrain - and skips the area for vmap and mmap generation.
![image](https://user-images.githubusercontent.com/2223066/109419460-d8f31d00-79cd-11eb-973e-fd778a407852.png)

Temporary solution is to generate the maptile in quick mode, which disables filtering underground terrain.

`MoveMapGen.exe 1 --tile 35,41 --quick`

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?
