### ISSUE TITLE
💬 [Discussion] Movement interpolation

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#971]
Why is movement interpolation regarded as unstable? It looked pretty awesome from the 2014 nost video. And is there a way to fix movement interpolation because it looks pretty fucking awesome and something I would love to have enabled.

https://www.youtube.com/watch?v=4JUwHIvEnZE

**Comment by Daribon** [comment]
In the 2014 nost video, they are showing movement from the players own point of view.
Correct way to showcase this would have been a character watching another character run around, or many characters run around.

The bad movement which you at times see in vmangos (and all other vnailla emulators) is really only visible if you watch other players move around.

Related issue: https://github.com/vmangos/core/issues/129

An interesting thing to note, is that for some reason patch 1.8 and below appears to have much more better looking player movement.

**Comment by jaywalker15262** [comment]
> In the 2014 nost video, they are showing movement from the players own point of view.
> Correct way to showcase this would have been a character watching another character run around, or many characters run around.
> 
> The bad movement which you at times see in vmangos (and all other vnailla emulators) is really only visible if you watch other players move around.
> 
> Related issue: #129
> 
> An interesting thing to note, is that for some reason patch 1.8 and below appears to have much more better looking player movement.

Indeed, that would remove the need for any wisps. You could just do side by side comparison with and without interpolation from the perspective of another player/players. Looking at your own PoV doesn't show you the realtime position of your character because the server doesn't update as quickly as your client, hence why the interpolation smoothens it out because it updates more frequently. My question is why is interpolation regarded as unstable, and what could be the reason behind patch 1.8 and below appearing to have better looking player movement? I like to believe it is not client related, but rather we dont manage it properly server side but I could be wrong.

**Comment by Daribon** [comment]
As stated in the related issue, it's probably something related to movement packets being different.
Especially since opcodes got changed in 1.9.0.

**Comment by jaywalker15262** [comment]
but why is movement interpolation considered unstable?

**Comment by ratkosrb** [comment]
You have to ask the nostalrius developers. I don't personally know any of them.

**Comment by punker85** [comment]
I am assuming that the client sends packets automatically at standard intervals similar to how the wisps spawned in the first half of the video and also that the server has no way to request additional movement packets from the client. With that info in consideration, the interpolation procedure would be doing some linear calculation and probably checking mmaps for valid movement. First, doing this 20x per second as in the 2nd half of the video would be very CPU intensive if done for every player when compared to updates every .5 seconds. Second, is the server going to broadcast more movement update packets to the nearby players with this functionality? If so, there is another concern of instability. Third, if a player makes jagged movement patterns by changing directions all the time there will be some weird patterns of interpolated movement paths that will be disconnected. If server updates movements with this info to players you might see some players warping around at times due to movement packets that could be sent at the end of an interpolation but just before server recieved the update from the moving player.

Additionally consider the following MANGOS forum thread which claims that 60% of their CPU process time was used for processing movement packets.  https://www.getmangos.eu/forums/topic/5210-10848-multithreaded-packet-processing/

**Comment by jaywalker15262** [comment]
Do any of you have an idea if it is possible to get the smooth movement we had in earlier patches and how it would be achieveable without being too cpu taxing?

Would be really huge and great change if we could achieve that. Many would love it.

EDIT: According to user real_namreeb on r/wowservers as to why movement interpolation is unstable:
"The reason is that the backing third-party library, detour, is not used in a thread-safe manner. Because of the high population, maps were divided into multiple threads. This division was done in a specific way to minimize the chance of a unit being on the boundary, but it can happen. When there are lots of units on the boundaries of two threads in the same map you increase the chance of a race condition. If you use only one thread per map I think it should be fine. This will work provided your population is less than 1000 or so."
